<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('fungsidate');
    }

    public function index()
    {
        $tanggal1 = date("Y-m-d");
        $tanggal2 = tgl_indo($tanggal1);
        $this->session->set_userdata('tanggal',$tanggal2); 
		$this->load->helper(array('form'));
		$this->load->view('login_view');
    }

    public function logout()
    {
        $this->session->unset_userdata('logined');
        session_destroy();
        redirect('login', 'refresh');
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */